on:
  workflow_run:
    workflows: ["MSBuild"] # Name of the msbuild.yml workflow
    types:
      - completed

jobs:
  release:
    name: Create Release
    runs-on: windows-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-binaries

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./binaries # Path to the binaries directory
          asset_name: build-binaries.zip
          asset_content_type: application/zip
