name: Publish

on:
  workflow_run:
    workflows: ["MSBuild"] # Name of the msbuild.yml workflow
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: windows-latest

    steps:
      - name: Check which workflow triggered
        run: echo "Triggered by workflow: ${{ github.event.workflow_run.workflow_id }}"
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-binaries # Name of the artifact to download
          path: ./binaries     # Where to save the artifact locally

      - name: Display structure of downloaded files
        run: ls -R binaries

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release:
            - Added new features
            - Improved performance
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./binaries
          asset_name: build-binaries.zip
          asset_content_type: application/zip
